### ISSUE TITLE
Recurring Event Download Support

### ISSUE THREAD

**Issue by davidatkinswwt** [transformstudios/statamic-events#27]
I have a multi-day event with the following:

```
multi_day: true
days:
  -
    date: '2022-04-16'
    start_time: '16:00'
    end_time: '17:15'
  -
    date: '2022-04-16'
    start_time: '17:45'
    end_time: '19:00'
  -
    date: '2022-04-17'
    start_time: '08:30'
    end_time: '09:45'
  -
    date: '2022-04-17'
    start_time: '10:15'
    end_time: '11:45'
  -
    date: '2022-04-17'
    start_time: '12:00'
    end_time: '13:15'
```

When downloading the event for Sat, April 16th 4:00pm - 5:15pm I receive a .ics file with a date and time 
Sat, April 16th 4:00pm - Sun, April 17th 1:15pm 

Any chance we'll see support recurring event downloads?
