### ISSUE TITLE
Issue with displaying multi date

### ISSUE THREAD

**Issue by mmai1554** [transformstudios/statamic-events#29]
Thank you for the plugin! 

Maybe I'm missing something but at the moment I'm not able to display an Event with multi days in a way it displays the multi date. So given the Entry (collection = Veranstaltungen):

```
---
id: 7bef5bf6-b6a3-4fae-b0f6-a8f4ed11e990
blueprint: veranstaltungen
title: 'MNC Test'
all_day: false
multi_day: true
days:
  -
    date: '2022-03-30'
  -
    date: '2022-04-01'
  -
    date: '2022-04-04'
recurrence: false
```
And this test template:
```
<ul>
    {{ events:between collection="veranstaltungen" from ="2022-01-01" to="2022-12-31" }}

    {{ if no_results }}
    <li>No Result</li>
    {{ else }}
    <li>
        <ol>
            {{ dates scope="veranstaltung" }}
            <li>
                {{ date }}
            </li>
            {{ /dates }}
        </ol>
    </li>

    {{ /if }}
    {{ /events:between }}
</ul>

```
outputs:
Collection Events:between

-         March 28th, 2022
-         March 28th, 2022
-         March 28th, 2022

The expected behaviour should be the output of the dates 2022-03-30, 2022-04-01 and 2022-04-04, no? 
How can I list the multi dates?
