### ISSUE TITLE
Event Download Links returning error

### ISSUE THREAD

**Issue by davidatkinswwt** [transformstudios/statamic-events#35]
Hey back again..😅

I've since updated the package and reviewed the upgrade guide. 

When downloading (or attempting to download) the event I receive an error when opening the .ics file. 

The same thing happens when the type is switched to google, yahoo, etc.

My event times are in a grid:

```
event_times:
  -
    all_day: false
    multi_day: false
    start_date: '2022-04-16'
    start_time: '16:00'
    end_time: '17:15'
    recurrence: '0'
  -
    all_day: false
    multi_day: false
    start_date: '2022-04-16'
    start_time: '17:45'
    end_time: '19:00'
    recurrence: '0'
  -
    all_day: false
    multi_day: false
    start_date: '2022-04-17'
    start_time: '08:30'
    end_time: '09:45'
    recurrence: '0'
```

After downloading the ics file is empty.

Wondering if you could shed any light on the situation or if this in fact an error. 

This is the error when importing:
<img width="372" alt="Screen Shot 2022-05-05 at 10 41 43 PM" src="https://user-images.githubusercontent.com/28378640/167063315-9297f507-fd87-4255-857b-af188ed8f52f.png">

Thanks again

**Comment by adnankussair** [comment]
Hey @davidatkinswwt! Welcome back. We'll take a looksie and get back to you shortly. Thanks for reporting.

**Comment by edalzell** [comment]
You have events in a grid? That's not supported right now, can you please explain your use case?

**Comment by davidatkinswwt** [comment]
It's left over from Events v3.3.3 when multi-day events were not working as expected.

During v3.3.3 I put single events into a grid which allowed me to save individual calendar events for a multi-day event with different start times. (See above event times grid).

Where if I had something like the following I would get an event that started on Jan 1 @ 6:30pm and end Jan 3 @ 8:00pm. My understanding of how the recurrence works may be flawed but I thought this would create 3 event times from Jan 1-3 all starting at 6:30pm and ending 8:00pm. 

```
event_times:
  - 
    all_day: false
    multi_day: false
    start_date: "2022-01-01"
    start_time: "18:30"
    end_time: "20:00"
    recurrence: daily
    end_date: "2022-01-03"
```

I did switch out the grid for just the "Event" fieldset and created a multi-day event with the following information and the issue persists. 

```
// v4.0, no grid
all_day: false
multi_day: true
days:
  - date: "2022-04-16"
    start_time: "16:00"
    end_time: "17:15"
  - date: "2022-04-16"
    start_time: "17:45"
    end_time: "19:00"
  - date: "2022-04-17"
    start_time: "08:30"
    end_time: "10:00"
  - date: "2022-04-17"
    start_time: "10:15"
    end_time: "12:00"
  - date: "2022-04-17"
    start_time: "12:15"
    end_time: "13:30"
```

Thanks
