### ISSUE TITLE
Addon settings for v3

### ISSUE THREAD

**Issue by 1stevengrant** [transformstudios/statamic-events#45]
Hey folks,
A couple of questions now that I'm integrating this into our project this week.

The docs make mention of addon settings but not sure where these would exist in v3.

Wondering also, if that's what's causing the illegal offset type in this snippet

```
{{ events:upcoming collection="stevens_events" limit="2" }}
{{ dates }}
...other entry data
{{ date }} <br>
{{ /dates }}
{{ /events:upcoming }}
```

**Comment by 1stevengrant** [comment]
spotted the `config/events.php` in the package. Copied that into my `config` directory and updated the collection to be used and error is the same.

**Comment by edalzell** [comment]
Can you post the top few lines if the error?

**Comment by 1stevengrant** [comment]
![](https://d.pr/i/SG1LwG+)

**Comment by 1stevengrant** [comment]
oh yeah, `type`

**Comment by edalzell** [comment]
Can I see the actual error please.

**Comment by 1stevengrant** [comment]
this is the entirety of it, or am I misunderstanding what you're asking?

![](https://d.pr/i/da1QCQ+)

**Comment by edalzell** [comment]
Can I please see your blueprint for this collection and a sample entry?

**Comment by 1stevengrant** [comment]
fieldset:

```
title: Event
fields:
  -
    handle: library
    field:
      max_items: 1
      mode: select
      collections:
        - libraries
        - locations
      display: Library
      type: entries
      icon: entries
      width: 33
      listable: hidden
  -
    handle: free
    field:
      type: toggle
      display: 'Is free event?'
      width: 33
  -
    handle: event_ticket_price
    field:
      input_type: text
      antlers: false
      display: 'Ticket Price (£)'
      type: text
      icon: text
      listable: hidden
      width: 33
      if:
        free: 'equals false'
  -
    handle: status
    field:
      options:
        '': Running
        Cancelled: Cancelled
        Postponed: Postponed
        Hidden: Hidden
      multiple: false
      clearable: false
      searchable: true
      taggable: false
      push_tags: false
      cast_booleans: false
      display: Status
      type: select
      icon: select
      width: 33
      listable: hidden
  -
    handle: online
    field:
      display: Online
      type: toggle
      icon: toggle
      width: 33
      listable: hidden
  -
    handle: recurring
    field:
      display: Recurring
      type: toggle
      icon: toggle
      width: 33
      listable: hidden
  -
    handle: recurrence
    field:
      options:
        0: None
        daily: Daily
        weekly: Weekly
        monthly: Monthly
        every: Every
      multiple: false
      clearable: false
      searchable: true
      taggable: false
      push_tags: false
      cast_booleans: false
      display: Recurrence
      type: select
      icon: select
      listable: hidden
      if:
        multi_day: 'equals false'
        recurring: 'equals true'
  -
    handle: interval
    field:
      display: Interval
      type: integer
      icon: integer
      listable: hidden
      if:
        recurrence: 'equals every'
      width: 50
  -
    handle: period
    field:
      options:
        days: Days
        weeks: Weeks
        years: Years
      multiple: false
      clearable: false
      searchable: true
      taggable: false
      push_tags: false
      cast_booleans: false
      display: Period
      type: select
      icon: select
      listable: hidden
      if:
        recurrence: 'equals every'
      width: 50
  -
    handle: multi_day
    field:
      display: 'Multi day?'
      type: toggle
      icon: toggle
      width: 50
      listable: hidden
  -
    handle: all_day
    field:
      display: 'All day'
      type: toggle
      icon: toggle
      width: 50
      listable: hidden
  -
    handle: except
    field:
      fields:
        -
          handle: date
          field:
            mode: single
            time_enabled: false
            time_required: false
            earliest_date: '1900-01-01'
            full_width: false
            inline: false
            columns: 1
            rows: 1
            display: Date
            type: date
            icon: date
            listable: hidden
      mode: table
      reorderable: true
      display: Except
      type: grid
      icon: grid
      listable: hidden
      if:
        recurrence: 'contains_any daily weekly monthly every'
  -
    handle: start_date
    field:
      width: 33
      mode: single
      time_enabled: false
      time_required: false
      earliest_date: '1900-01-01'
      full_width: false
      inline: false
      columns: 1
      rows: 1
      display: 'Start date'
      type: date
      icon: date
      listable: hidden
      if:
        multi_day: 'equals false'
  -
    handle: start_time
    field:
      width: 33
      display: 'Start time'
      type: time
      icon: time
      listable: hidden
      if:
        multi_day: 'equals false'
        all_day: 'equals false'
  -
    handle: end_time
    field:
      width: 33
      display: 'End time'
      type: time
      icon: time
      listable: hidden
      if:
        multi_day: 'equals false'
        all_day: 'equals false'
  -
    handle: days
    field:
      fields:
        -
          handle: date
          field:
            mode: single
            time_enabled: false
            time_required: false
            earliest_date: '1900-01-01'
            full_width: false
            inline: false
            columns: 1
            rows: 1
            display: Date
            type: date
            icon: date
            listable: hidden
        -
          handle: start_time
          field:
            display: 'Start time'
            type: time
            icon: time
            listable: hidden
        -
          handle: end_time
          field:
            display: 'End time'
            type: time
            icon: time
            listable: hidden
      mode: table
      reorderable: true
      display: Days
      type: grid
      icon: grid
      listable: hidden
      min_rows: 2
      add_row: 'Add Day'
      if:
        multi_day: 'equals true'
  -
    handle: end_date
    field:
      mode: single
      time_enabled: false
      time_required: false
      earliest_date: '1900-01-01'
      full_width: false
      inline: false
      columns: 1
      rows: 1
      display: 'End date'
      type: date
      icon: date
      listable: hidden
      if:
        recurrence: 'contains_any daily weekly monthly every'
```

test entry

```
---
title: 'Test Entry'
library: 70bf3365-c974-40fd-be7d-a36e28833b5c
free: false
online: true
recurring: true
recurrence: weekly
multi_day: false
all_day: true
start_date: '2021-03-09'
days:
  -
    date: null
    start_time: null
    end_time: null
  -
    date: null
    start_time: null
    end_time: null
updated_by: 6e81f3b2-6620-4c7e-8b5c-0e36c59974ba
updated_at: 1615225714
id: f73163b7-211c-4f7d-96d3-aa3547c102bf
---
```
