### ISSUE TITLE
Recurring events listing with day of event...

### ISSUE THREAD

**Issue by skoontastic** [transformstudios/statamic-events#49]
I'm on `v4.0.7` and seeing this behavior. Maybe I'm doing something wrong? My expectation would be that the `start` for recurring date entries would output the date of that instance.

Event entry:

```yaml
---
id: 7898ead6-ed87-4706-8353-21d04efb017a
blueprint: event
title: 'Library Closed'
all_day: true
multi_day: false
thumbnail: closed.jpeg
updated_by: 7147e673-5b3c-490f-a963-872a0dba66bd
updated_at: 1671806192
start_date: '2022-12-23'
recurrence: daily
end_date: '2022-12-26'
---
```

Template snippet:
```blade
<h2 class="font-serif text-2xl font-semibold">Events</h2>
<ul>
    {{ events:in next="7 days" }}

        <li> <span class="font-bold">{{ title }}</span>
            {{ start format="D M j" }}
            {{ unless all_day }}
                {{ start format="g:i a" }}
            {{ /unless }}
            {{ if end_date }}
                - {{ end_date format="D M j" }}
            {{ /if }}
            {{ if has_end_time }}
                - {{ end format="g:i a" }}
            {{ /if }}
        </li>
    {{ /events:in }}
</ul>

```

Output:
Library Closed Fri Dec 23 - Mon Dec 26
Library Closed Fri Dec 23 - Mon Dec 26
Library Closed Fri Dec 23 - Mon Dec 26
Library Closed Fri Dec 23 - Mon Dec 26
