### ISSUE TITLE
If recurring event is all and recurrence ends on the last day of event, the occurrence is not shown.

### ISSUE THREAD

**Issue by edalzell** [transformstudios/statamic-events#81]
For example, this data:

```yaml
---
id: 16e5c861-4533-45e8-97ad-c521a9016fc0
blueprint: event
title: 'Test Event'
has_livestream: false
recurrence: every
timezone: America/Chicago
all_day: true
interval: 2
period: weeks
start_date: '2024-02-01'
end_date: '2024-02-29'
wrapper_classes: 'pt-5 pb-0'
disable_header: false
disable_footer: false
updated_by: cba0aed3-26f9-4ca9-a67f-8261a605d37b
updated_at: 1707862058
---
```

Won't show an event on the 29th. If add a time to the event it does.
